

export const lang = [
    {
      logo: 'myh',
      videos: 'videos',
      relVideos: 'related videos',
      video : 'video',
      showMore: 'show more',
      showLess: 'show less',
      share: 'share',
      download: 'download',
      save: 'save',
      report: 'report',
      comments: 'comments',
      views: 'views',
      replies: 'replies', 
      subscribe: 'subscribe' , 
      subscribed: 'subscribed' ,
      subscribers: 'subscribers' ,
      home: 'home',
      shorts: 'shorts',
      live: 'live',
      playlists: 'playlists',
      about: 'about',
      dislike: 'dislike',
      description: 'description',
      stats: 'stats',
      joined: 'joined',
      retry: 'retry',
      search: 'search',
      language: 'Language'
    },
    {
        logo: 'myh',
        videos: 'الفيديوهات',
        relVideos: 'محتوى مشابه',
        video : 'فيديو',
        showMore: 'أظهر أكثر',
        showLess: 'أظهر أقل',
        share: 'مشاركه',
        download: 'تحميل',
        save: 'حفظ',
        report: 'بلاغ',
        comments: 'تعليق',
        views: 'مشاهدة',
        replies: 'الرد', 
        subscribe: 'اشتراك' , 
        subscribed: 'مشترك' ,
        subscribers: 'مشترك' ,
        home: 'الصفحة الرئيسية',
        shorts: 'shorts',
        live: 'بث مباشر',
        playlists: 'قوائم التشغيل',
        about: 'لمحة',
        dislike: 'الغا الإعجاب',
        description: 'الوصف',
        stats: 'الإحصائيات',
        joined: 'الإنضمام',
        retry: 'إعادة المحاولة',
        search: 'ابحث',
        language: 'اللغة'
      }
]