

export const language = {
  en: {
      logo: 'myh',
      videos: 'videos',
      relVideos: 'related videos',
      video : 'video',
      showMore: 'show more',
      showLess: 'show less',
      share: 'share',
      download: 'download',
      save: 'save',
      report: 'report',
      comments: 'comments',
      views: 'views',
      replies: 'replies', 
      subscribe: 'subscribe' , 
      subscribed: 'subscribed' ,
      subscribers: 'subscribers' ,
      home: 'home',
      shorts: 'shorts',
      live: 'live',
      playlists: 'playlists',
      community: 'community',
      channels: 'channels',
      about: 'about',
      dislike: 'dislike',
      description: 'description',
      stats: 'stats',
      joined: 'joined',
      retry: 'retry',
      search: 'search',
      language: 'Language',
      clip: 'clip',
      trending: 'trending',
      music: 'music',
      gaming: 'gaming',
      sports: 'sports',
      subscribtions: 'subscribtions',
      labrary: 'labrary',
      history: 'history',
      yourVideos: 'your videos',
      watchLater: 'watch later',
      likedVideos: 'liked videos',
      sittings: 'sittings',
      reportHistory: 'report history',
      help: 'help',
      sendFeedback: 'send feedback',
      latest: 'latest',
      popular: 'popular',
      oldest: 'oldest',
      dateAdded: 'date added',
      lastVideoAdded: 'last video added',
      links: 'links',
      palyAll: 'play all',
      votes: 'votes',
    },
   ar: {
        logo: 'myh',
        videos: 'الفيديوهات',
        relVideos: 'محتوى مشابه',
        video : 'فيديو',
        showMore: 'أظهر أكثر',
        showLess: 'أظهر أقل',
        share: 'مشاركه',
        download: 'تحميل',
        save: 'حفظ',
        report: 'بلاغ',
        comments: 'تعليقا',
        views: 'مشاهدة',
        replies: 'رد', 
        subscribe: 'اشتراك' , 
        subscribed: 'مشترك' ,
        subscribers: 'مشترك' ,
        home: 'الصفحة الرئيسية',
        shorts: 'shorts',
        live: 'بث مباشر',
        playlists: 'قوائم التشغيل',
        community: 'الملصقات',
        channels: 'القنوات',
        about: 'لمحة',
        dislike: 'الغا الإعجاب',
        description: 'الوصف',
        stats: 'الإحصائيات',
        joined: 'الإنضمام',
        retry: 'إعادة المحاولة',
        search: 'ابحث',
        language: 'اللغة',
        clip: 'قص',
        trending: 'شايع',
        music: 'موسيقى',
        gaming: 'العاب',
        sports: 'رياضة',
        subscribtions: 'الإشتراكات',
        labrary: 'المكتبة',
        history: 'السجل',
        yourVideos: 'فيديوهاتك',
        watchLater: 'شاهد لاحقا',
        likedVideos: 'فيديوهات اعجبتك',
        sittings: 'الضبط',
        reportHistory: 'سجل البلاغات',
        help: 'المساعدة',
        sendFeedback: 'ارسل تقرير',
        latest: 'احدث',
        popular: "اشهر",
        oldest: 'اقدم',
        dateAdded: '(بدا من الأحدث)تاريخ الإضافة',
        lastVideoAdded: 'الفيديو الاخير الذي تمت إضافته',
        links: 'روابط',
        palyAll: 'تشغيل الكل',
        votes: 'صوت',
      }
  }